### ISSUE TITLE
Invalid alias name [npms-write], an index exists with the same name as the alias

### ISSUE THREAD

**Issue by slang800** [npms-io/npms-analyzer#21] opened 2016-04-19 01:33 UTC
```bash
$ ./cli.js scoring --log-level silly
verb util/bootstrap Elasticsearch is ready
verb util/bootstrap CouchDB for npms is ready
info Starting scoring cycle
info scoring/prepare Preparing scoring..
verb scoring/prepare Gathered elasticsearch info.. { indices: [ 'npms-1461027817406' ],
verb scoring/prepare   aliases: { read: [], write: [] } }
verb scoring/prepare Created new index { index: 'npms-1461028580891' }
ERR! Scoring cycle failed { err: 
ERR!    { [Error: [invalid_alias_name_exception] Invalid alias name [npms-write], an index exists with the same name as the alias, with { index=npms-1461028580891 }]
ERR!      status: 400,
ERR!      displayName: 'BadRequest',
ERR!      message: '[invalid_alias_name_exception] Invalid alias name [npms-write], an index exists with the same name as the alias, with { index=npms-1461028580891 }',
ERR!      path: '/_aliases',
ERR!      query: {},
ERR!      body: { error: [Object], status: 400 },
ERR!      statusCode: 400,
ERR!      response: '{"error":{"root_cause":[{"type":"invalid_alias_name_exception","reason":"Invalid alias name [npms-write], an index exists with the same name as the alias","index":"npms-1461028580891"}],"type":"invalid_alias_name_exception","reason":"Invalid alias name [npms-write], an index exists with the same name as the alias","index":"npms-1461028580891"},"status":400}',
ERR!      toString: [Function],
ERR!      toJSON: [Function] } }
ERR! Stack:
ERR! at respond (/usrdata/proj/npms-analyzer/node_modules/elasticsearch/src/lib/transport.js:289:15)
ERR!     at checkRespForFailure (/usrdata/proj/npms-analyzer/node_modules/elasticsearch/src/lib/transport.js:248:7)
ERR!     at HttpConnector.<anonymous> (/usrdata/proj/npms-analyzer/node_modules/elasticsearch/src/lib/connectors/http.js:164:7)
ERR!     at IncomingMessage.wrapper (/usrdata/proj/npms-analyzer/node_modules/elasticsearch/node_modules/lodash/index.js:3095:19)
ERR!     at emitNone (events.js:85:20)
ERR!     at IncomingMessage.emit (events.js:179:7)
ERR!     at endReadableNT (_stream_readable.js:906:12)
ERR!     at nextTickCallbackWith2Args (node.js:475:9)
ERR!     at process._tickCallback (node.js:389:17)
ERR! From previous event:
ERR!     at prepare (/usrdata/proj/npms-analyzer/lib/scoring/prepare.js:61:6)
ERR!     at cycle (/usrdata/proj/npms-analyzer/cli/scoring.js:52:5)
ERR!     at /usrdata/proj/npms-analyzer/cli/scoring.js:110:21
ERR!     at processImmediate [as _immediateCallback] (timers.js:383:17)
ERR! From previous event:
ERR!     at /usrdata/proj/npms-analyzer/cli/scoring.js:110:10
ERR! From previous event:
ERR!     at Object.Promise.resolve.then.prepare.tap.then.exports.builder.exports.handler.bootstrap.spread [as handler] (/usrdata/proj/npms-analyzer/cli/scoring.js:103:6)
ERR!     at Object.self.runCommand (/usrdata/proj/npms-analyzer/node_modules/yargs/lib/command.js:113:22)
ERR!     at parseArgs (/usrdata/proj/npms-analyzer/node_modules/yargs/yargs.js:632:24)
ERR!     at Object.Yargs.Object.defineProperty.get [as argv] (/usrdata/proj/npms-analyzer/node_modules/yargs/yargs.js:592:16)
ERR!     at Object.<anonymous> (/usrdata/proj/npms-analyzer/cli.js:34:1)
ERR!     at Module._compile (module.js:413:34)
ERR!     at Object.Module._extensions..js (module.js:422:10)
ERR!     at Module.load (module.js:357:32)
ERR!     at Function.Module._load (module.js:314:12)
ERR!     at Function.Module.runMain (module.js:447:10)
ERR!     at startup (node.js:140:18)
ERR!     at node.js:1001:3
ERR! 
info Waiting 1 hour before running the next cycle.. { now: '2016-04-19T01:16:21.080Z' }
stat process pid: 8245; memory: 45.15 MB; uptime: 21 seconds
^C
```

...I'll start reading up on Elasticsearch

**Comment by satazor** [comment] 2016-04-19 09:47
What version of es are you using?

**Comment by slang800** [comment] 2016-04-19 15:48
```bash
$ elasticsearch --version
Version: 2.3.1, Build: bd98092/2016-04-04T12:25:05Z, JVM: 1.7.0_95
```

...By deleting all the indices that got added, I managed to fix this. I assume it just got into a weird state, but I haven't been able to reproduce it.

**Comment by satazor** [comment] 2016-04-20 02:49
Thats really strange, it never happened with ne but I will take a closer look

**Comment by satazor** [comment] 2016-04-20 12:13
I've upgrade to the elasticsearch version you have, tried several scenarios and couldn't reproduce. I will close this, feel free to re-open if it happens again.

**Closed by satazor** 2016-04-20 12:13 UTC
