### ISSUE TITLE
Searching for "polymer" gives an odd first result

### ISSUE THREAD

**Issue by dandv** [npms-io/npms-analyzer#79] opened 2016-08-16 19:39 UTC
https://npms.io/search?term=polymer shows https://www.npmjs.com/package/polymer as the first result.

I'm not sure [what's wrong with https://www.npmjs.com/package/Polymer](https://github.com/Polymer/polymer/issues/326#issuecomment-240216349) that NPMJS thinks it has no README, but that, or better yet, https://www.npmjs.com/package/@polymer/polymer, should be the first result.

https://www.npmjs.com/package/npm-polymer-elements, published by a personality, doesn't show up until the 5th page of results or so.

Polymer packages are at https://www.npmjs.com/~polymer.

**Comment by satazor** [comment] 2016-08-20 10:56
Polymer has a bad score in npms, needs to be investigated why.

**Comment by satazor** [comment] 2016-09-26 20:54
@dandv I've investigated and this is a duplicate of #47. Once that is sorted out, polymer should have a good score and should be shown first.

**Closed** 2016-09-26 20:55 UTC
Labels: investigate
