### ISSUE TITLE
Multiple packages point to popular GitHub repos

### ISSUE THREAD

**Issue by atduarte** [npms-io/npms-analyzer#25] opened 2016-04-26 20:05 UTC
Multiple packages point to popular GitHub repos and most have almost no downloads. Searching for jquery this is very clear: 

https://www.npmjs.com/package/jquery-compat
https://www.npmjs.com/package/jquery1
https://www.npmjs.com/package/shimney-jquery

Since these repos all point to the JQuery GitHub Repo, they end up having a high score, but they shouldn't.

This affects current searches, but could affect even more in the future if some scammers discover this issue.

**Suggestion**:  If there's more than one package with the same GitHub repo only consider the GitHub stats for the one with more downloads on npm.

**Comment by satazor** [comment] 2016-04-26 20:10
@atduarte your suggestion could break some valid use-cases, e.g.: bower and bower-canary

Another suggestion is to check if the publisher of the module is in the top100 list of GitHub contributors. This would work in 99% of the cases and is relatively easily to implement because it's self contained (doesn't require to do additional queries to CouchDB).

**Comment by atduarte** [comment] 2016-04-26 20:20
@satazor how would we check? By the username? SGFM. 

Noticed now that jquery-compat is published by one of the top 100 Jquery contributors, for example :+1:

**Comment by satazor** [comment] 2016-04-26 20:27
The check would actually be hard. The problem is that the contributors API response from GitHub only gives us an username. It would require an additional request per contributor to have additional information such as full name and email.

The npm metadata includes an email its npm username. We could do some hackery with `git` to list all the emails in the cloned git repository and check against the npm's email. Though, that would require us to use the downloader/git instead of downloader/github.

**Comment by sindresorhus** [comment] 2016-04-28 09:08
> Another suggestion is to check if the publisher of the module is in the top100 list of GitHub contributors. 

That sounds like a bad hack. There are still lots of duplicates for modules from people not in that list.

> your suggestion could break some valid use-cases, e.g.: bower and bower-canary

Both of those are published by the same user though. So would be easy to detect.

**Comment by satazor** [comment] 2016-04-29 09:01
I think we have good solution which is a mix of several proposed solutions:

Let's take `jquery1` as an example. Its module name in npm is `jquery1` which `repository` points to the officlal jquery one. Since we download the source code from the repository, there's a mismatch between the downloaded package.json `name` property and the module name: `jquery1` !== `jquery`.

To solve the `bower` & `bower-canary` use case, we can check if the publisher of `jquery1` is within the list of maintainers of `jquery` which is quite easy.

**Comment by atduarte** [comment] 2016-04-29 09:19
Checking if the publisher is the same user from the "official" repo would also be good.

Something like:
```
npmPackage = the one we are checking if it's good
packageJsonName = name that's on the repository's package.json

if (packageJsonName == npmPackage.name) return true

officialPackage = searchNpm(packageJsonName)
if (officialPackage.publisher == npmPackage.publisher) return true

if (npmPackage.publisher in repository.top100Contributors) return true;

return false;
```

**Comment by satazor** [comment] 2016-04-29 09:30
I think we can make it simpler, since we have a `maintainers` property in the couchdb document, which is a list of people that has publish permissions for a given module. Having that said:

```js
// package data is a complete couchdb document
// package json is just the package json, extracted from a specific version of the package data

npmPackageJson =  the package.json we are checking if it's good
packageData = the repository's package data
packageJson = the repository's package.json

if (packageJson.name== npmPackageJson.name) return true

packageData = searchNpm(packageJson.name)
if (packageData.maintainers contains npmPackageJson._npmUser) return true  // aka publisher

return false;

**Comment by satazor** [comment] 2016-04-29 10:51
Did I miss anything in the scenarios above?

**Comment by satazor** [comment] 2016-05-01 10:54
@atduarte there's a PR in #25, can you take a look? Also, this would require a full analisys of the npm ecosystem, which as you know, happens  in 15 days. What we can do is to enqueue modules that appear in popular searches, such as jquery and others. Suggestions?

**Comment by satazor** [comment] 2016-05-02 15:31
I've merged myself because of the (precious) time we are loosing.

**Closed** 2016-05-02 15:30 UTC
